[tool.poetry]
name = "jobdex"
version = "0.1.0"
description = ""
authors = ["Venu Vardhan Reddy Tekula <vt2182@nyu.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
